### ISSUE TITLE
图片Base64编码

### ISSUE THREAD

**Issue by cy0707** [cy0707/about_html#4]
## 前言

很早以前就听说过图片Base64编码，一直没有好好的了解，所以进行总结一下。

[博文链接](http://www.cnblogs.com/coco1s/p/4375774.html?utm_source=tuicool&utm_medium=referral)
[知乎讨论](https://www.zhihu.com/question/31155574?sort=created)

## 什么是base64编码?

图片的 base64 编码就是可以将一副图片数据编码成一串字符串，使用该字符串代替图像地址。

这样做有什么意义呢？我们知道，我们所看到的网页上的每一个图片，都是需要消耗一个 http 请求下载而来的。

没错，不管如何，图片的下载始终都要向服务器发出请求，要是图片的下载不用向服务器发出请求，而可以随着 HTML 的下载同时下载到本地那就太好了，而 base64 正好能解决这个问题。

####  在css里面的写法

```css
#fkbx-spch, #fkbx-hspch {
  background: url(data:image/gif;base64,R0lGODlhHAAmAKIHAKqqqsvLy0hISObm5vf394uLiwAAAP///yH5B…EoqQqJKAIBaQOVKHAXr3t7txgBjboSvB8EpLoFZywOAo3LFE5lYs/QW9LT1TRk1V7S2xYJADs=) no-repeat center;
}
```

####  在html里面的写法

```html
<img src="data:image/gif;base64,R0lGODlhHAAmAKIHAKqqqsvLy0hISObm5vf394uLiwAAAP///yH5B…EoqQqJKAIBaQOVKHAXr3t7txgBjboSvB8EpLoFZywOAo3LFE5lYs/QW9LT1TRk1V7S2xYJADs=">

```

当然 base64 编码不仅仅运用在图片编码，还可以：

`thunder://QUFodHRwOi8vZG93bi5zYW5kYWkubmV0L3RodW5kZXI3L1RodW5kZXI3LjEuNS4yMTUyLmV4ZVpa`

迅雷的“专用地址”也是用 Base64 加密的

####  使用 base64 的一个前提，那就是被 base64 编码的图片足够尺寸小

图片被编码之后，生成的字符串编码大小一般而言都会比原文件稍大一些。即便 base64 编码能够被 gzip 压缩，压缩率能达到 50% 以上，想象一下，一个元素的 css 样式编写居然超过了 2000个 字符，那对 css 整体的可读性将会造成十分大的影响，代码的冗余使得在此使用 base64 编码将得不偿失。

####  如果图片足够小且因为用处的特殊性无法被制作成雪碧图（CssSprites），在整个网站的复用性很高且基本不会被更新。

背景图 background-image 。在很多地方，我们会制作一个很小的图片大概是几px*几px，然后平铺它页面当背景图。因为是背景图的缘故，所以无法将它放入雪碧图，而它却存在网站的很多页面，这种图片往往只有几十字节，却需要一个 http 请求，十分不值得。那么此时将它转化为 base64 编码，何乐而不为。

## 使用base64图片的弊端

而是因为如果把大图片编码到 html / css 中，会造成后者体积明显增加，明显影响网页的打开速度。
如果用外链图片的话，图片可以在页面渲染完成后继续加载，不会造成阻塞。

如果 base64 是被编码到 css/js 中，是可以缓存的，因为 css/js 文件可以缓存。

使用 base64 的另外一个弊端是 IE 的兼容性问题。IE 8 以下不支持 data url，IE 8 开始支持 data url，却有大小限制，32k（未测试）。

还有一个问题是，如果构建工具比较落后（或者没有构建工具），手动插入 base64 是很蛋疼的，器会卡到哭。

## 更便捷的将图片转化为Base64编码　　

就是利用 Chrome 浏览器。在 chrome 下新建一个窗口，然后把要转化的图片直接拖入浏览器，打开控制台，点 Source，如下图所示，点击图片，右侧就会显示该图片的 base64 编码，是不是很方便。

![base](https://cloud.githubusercontent.com/assets/15865210/20591064/a1d13b50-b261-11e6-8232-5ae514c4d71b.jpg)
